vich_uploader:
    db_driver: orm
    mappings:
        poster_image:
            uri_prefix: /uploads/posters
            upload_destination: '%kernel.project_dir%/public/uploads/posters'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_remove: true
            delete_on_update: true
        post_image:
            uri_prefix: /uploads/posts
            upload_destination: '%kernel.project_dir%/public/uploads/posts'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_remove: true
            delete_on_update: true
